import { StyleSheet, Dimensions } from 'react-native'

const styles = StyleSheet.create({
    container:{
        flex:1,
    },
    header:{
        width:Dimensions.get('window').width,
        height:62,
        backgroundColor:'#075E55',
        flexDirection:'row',
        elevation:5,
        justifyContent:'space-between'
    },
    toHorizontal:{
        flexDirection:'row'
    },
    backButton:{
        alignItems:'center',
        justifyContent:'center',
        flexDirection:'row',
        padding:8,
        borderRadius:64,
    },
    perfilImage:{
        height:38,
        width:38,
        borderRadius:20
    },
    backgroundImage:{
        flex:1,
        resizeMode:"stretch"
    },
    textContainer:{
        alignItems:'flex-start',
        justifyContent:'center'
    },
    nome:{
        color:'#FFF',
        fontFamily:'Roboto_500Medium',
        fontSize:18
    },
    online:{
        color:'#FFF',
        fontSize:13,
    },
    iconsContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingHorizontal:8
    },
    headerIcon:{
        paddingHorizontal:8,     
    },
    messagesContainer:{
        flex:1,
        paddingHorizontal:10,
        paddingVertical:0,
    },
    inputContainer:{
        width:Dimensions.get('window').width,
        height:64,
        backgroundColor:'transparent',
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:8,
    },
    inputBox:{
        width: Dimensions.get('window').width - 72,
        minHeight:48,
        borderRadius:22,
        backgroundColor:'#FFF',
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:16,
        paddingVertical:2,
        
    },
    input:{
        flex:1,
        marginLeft:8,
        fontSize:16,
        textAlignVertical:"center",
        textAlign:"left"
    },
    audioBox:{
        height:52,
        width:52,
        backgroundColor:'#00887A',
        alignItems:'center',
        justifyContent:'center',
        marginLeft:4,
        borderRadius:26,
    },
    inputIcon:{
        marginLeft:24,
    }
});

export default styles;